name: superf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.20.3
  - pandas
  - xarray
  - netcdf4
  - matplotlib
  - scipy
  - bottleneck
  - numexpr
  - pip
  - geopandas
  - pip:
      - superflexpy
